"""feat:add_users_table

Revision ID: 862fd3323387
Revises: 
Create Date: 2024-06-01 07:46:30.899381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862fd3323387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('citizenshipCard', sa.Numeric(precision=15), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['citizenshipCard'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('lastName')
        batch_op.drop_column('name')
        batch_op.drop_column('citizenshipCard')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
